### ISSUE TITLE
No longer works with private "Watch Later" list

### ISSUE THREAD

**Issue by MisterTickle** [nrednav/youtube-playlist-duration-calculator#14]
Many thanks for a great plugin! Since today I'm not seeing the duration for my own "watch later" list, which I use a lot!
Is this a bug introduced by the recent re-factoring perhaps, or YouTube has changed something to break it?

![image](https://user-images.githubusercontent.com/20239099/200170765-805da641-de86-4b80-a370-3fb11dbbf41c.png)

To reproduce, the two videos in my WL list currently are
https://www.youtube.com/watch?v=ZyoXdgcmOa0
https://www.youtube.com/watch?v=u7D4aBKLoa4

(for clarity, it works fine with my other watchlists, eg this one
![image](https://user-images.githubusercontent.com/20239099/200170979-e52f684c-2472-4cac-90a9-19430ef034c6.png)
although I would like to remove the large gaps above "total duration" and below "videos not counted".

It always used to work with my Watch Later list.)

**Comment by nrednav** [comment]
Hi @MisterTickle, thanks for reporting this. Will try to get a fix out soon 👍

**Comment by MisterTickle** [comment]
Awesome @nrednav , thank you so much! :)

**Comment by MisterTickle** [comment]
New version 2.0.2 is working well! Thank you so much!

**Comment by nrednav** [comment]
Glad to hear that @MisterTickle 👍

Unfortunately you may need to continue using the unpacked version for a while, since v2.0.1 is still under review, and I can only submit v2.0.2 for review after that.

**Comment by starcat13** [comment]
Thank you, works for me too (Firefox)
