### ISSUE TITLE
showing "NaN:NaN:NaN" when there's a premiere in the playlist

### ISSUE THREAD

**Issue by SteffoSpieler** [nrednav/youtube-playlist-duration-calculator#17]
I know there's already an issue (#14), but I'm using version 2.0.2 with firefox.
If more infos are needed just ask me ^^

Update: I now know why there are problems calculating in my watch later!
When there's a premiere in the playlist, it fails calculating the duration!

**Comment by MisterTickle** [comment]
I've had some odd durations reported in my Watch Later list recently using 2.0.2, not "Nan" style but obviously-wrong durations.

This is really a lot longer than 49 minutes. Sometimes, reloading the page fixes it. Sometimes not.
![image](https://user-images.githubusercontent.com/20239099/206205531-d059f278-6c5c-4199-83d2-fc5d3d2c5c1c.png)

![image](https://user-images.githubusercontent.com/20239099/206205765-c0f523b3-e7b3-4df1-8552-ebcc55c8ff73.png)

It should be more like 11 hours.
