### ISSUE TITLE
Uncaught TypeError: Reduce of empty array with no initial value

### ISSUE THREAD

**Issue by MisterTickle** [nrednav/youtube-playlist-duration-calculator#19]
This happens with release 2.0.2 which I've loaded from disc as an unpacked extension.

![image](https://user-images.githubusercontent.com/20239099/211198978-80625900-65b0-4ca2-8770-372ec306f6fa.png)

I think this might be why I've had some wildly changing times on my "watch later" playlist recently.

**Comment by nrednav** [comment]
Apologies for the late response, this should be fixed in 2.1.0 via #31
