### ISSUE TITLE
zh_CN revised carefully, but not displayed

### ISSUE THREAD

**Issue by iaendi** [nrednav/youtube-playlist-duration-calculator#38]
[messages.json](https://github.com/nrednav/youtube-playlist-duration-calculator/files/14841364/messages.json)
This is the revised zh_CN json file, I checked every Chinese translation, now it looks fine.

I installed the v2.1.0-beta.7, but didn't find how to switch into zh_CN.
I tried to change IP address from Taiwan to Hong Kong, not working.

<img width="616" alt="image" src="https://github.com/nrednav/youtube-playlist-duration-calculator/assets/130339496/4d1f9643-8502-495d-8f76-ecc3c7034dcc">

<img width="969" alt="image" src="https://github.com/nrednav/youtube-playlist-duration-calculator/assets/130339496/4a4279d8-6701-4579-bc04-b89593e81867">

2024-04-03
By: Yong

**Comment by nrednav** [comment]
Thank you for the updated translations @iaendi.
The locale detection issues should be fixed in 2.1.0-beta.8 via #41 and #42
