### ISSUE TITLE
Incorrect Sorting of Video Play Counts in Chinese Interface

### ISSUE THREAD

**Issue by iaendi** [nrednav/youtube-playlist-duration-calculator#39]
### **Issue:**
 The sorting of video play counts is incorrect on the Chinese interface. Videos with fewer than 10,000 views are appearing above videos with several million views.
<img width="1114" alt="image" src="https://github.com/nrednav/youtube-playlist-duration-calculator/assets/130339496/1afe287c-3d23-41bf-98ff-5b2d3566a3db">

### **Steps to Reproduce:**

1. View the list of videos sorted by play count in the English interface, noting the correct order.
2. Switch to the Chinese interface.
3. Observe that videos with play counts lower than 10,000 (displayed with four digits) are ranked above those with several million views (displayed as a three-digit number followed by the Chinese character for "ten thousand").

### **Analysis:** 
The issue seems to stem from the fact that the Chinese interface uses “万” (10k) as the unit for play counts. The sorting algorithm appears to only consider the numeric part of the play count, disregarding the unit. This problem may also occur in other language interfaces with different units of measurement.

### **Expected Result:** 
Videos should be sorted based on the absolute size of their play counts, regardless of the unit displayed.

### **Possible Solutions:**

**Option A:** Modify the code to fetch and sort videos by their raw play count numbers, without units.
**Option B:** Enhance the code to recognize common numerical units (which vary by country) and sort based on the rules corresponding to these units. This approach is more complex, as it must account for various units such as "万" (10^4), "亿" (10^8), and "兆" (10^12) in Chinese, among others.

### **Conclusion:** 
It is recommended to sort videos by the absolute size of their play counts, using raw numbers rather than numbers with units, to ensure accurate sorting across different language interfaces.

**Comment by nrednav** [comment]
Thank you the detailed issue @iaendi. This should hopefully be fixed in 2.1.0-beta.8 via #41
