### ISSUE TITLE
Total duration in chaos

### ISSUE THREAD

**Issue by iaendi** [nrednav/youtube-playlist-duration-calculator#48]
Youtube Playlist Duration Calculator v2.1.0 official Chrome extension

I noticed the total duration number (135037 hours) is far bigger than the correct value (should be about 48 or 49 hours).
![WX20240413-094444@2x](https://github.com/nrednav/youtube-playlist-duration-calculator/assets/130339496/e3d9bd9f-00af-40c4-822b-adab52d3c044)

When I refreshed the page, the duration changed in other random number. (123159 hours)
![WX20240413-094609@2x](https://github.com/nrednav/youtube-playlist-duration-calculator/assets/130339496/d85c2e61-906c-4f9e-b683-c5a426836071)

I tried to remove the recent 2 or 3 videos from the playlist, the duration was still wrong. (No photos of this test)

I added the removed videos back, exactly the same 54 videos as earlier, but got different duration (126791 hours, then 119353 hours), and the number remained 119353 when I quickly refreshed several times.
https://github.com/nrednav/youtube-playlist-duration-calculator/assets/130339496/15574c7a-8569-4cc6-b8ac-bf19636c95bf

After 10 minutes or so, I refreshed the page, got another wrong number.
![WX20240413-100853@2x](https://github.com/nrednav/youtube-playlist-duration-calculator/assets/130339496/5130a422-7129-4d4b-bdbd-3ea7eed83a32)

So I removed all the 9 new videos added yesterday, found the total duration was wrong.
When adding them back one by one, the error remains, as shown in the video below. 
Sorry for the video quality, had to keep the size less than 10MB.
<img width="431" alt="image" src="https://github.com/nrednav/youtube-playlist-duration-calculator/assets/130339496/51f8cd74-5aec-4ca1-98d5-330129afa91b">

https://github.com/nrednav/youtube-playlist-duration-calculator/assets/130339496/97cece1c-80a0-4e33-ae31-7127432f5827

**Comment by nrednav** [comment]
Hi @iaendi, thank you for letting me know, I can confirm the same is happening for me, I will investigate further 👍

**Comment by nrednav** [comment]
Update: I've identified the issue and have a fix in the works

**Comment by nrednav** [comment]
@iaendi I have just submitted v2.1.1 to the chrome & firefox stores for approval. In the meantime you can also access it here: https://github.com/nrednav/youtube-playlist-duration-calculator/releases/tag/v2.1.1

**Comment by nrednav** [comment]
v2.1.1 was finally approved for Chrome: https://chrome.google.com/webstore/detail/youtube-playlist-duration/pijbakhgmhhadeakaocjfockpndcpobk

Closing this issue, feel free to re-open if the issue happens again 👍
