### ISSUE TITLE
Not working on watch later playlist

### ISSUE THREAD

**Issue by Destral1** [nrednav/youtube-playlist-duration-calculator#50]
Nothing is displayed on the watch later playlist, as if the extension wasn't installed. It works fine in other playlists.

**Comment by nrednav** [comment]
Hi @Destral1, thanks for reporting this. May I please get some more information:

- Browser (Chrome or Firefox)
- OS (Windows, macOS or Linux)
- Extension Version
- Screenshot(s) of the issue if possible

Could you also please try the following:

- Navigate to the Watch Later playlist
- Open the browser console
  - Chrome: Ctrl + Shift + J (Windows), Cmd + Option + J (Mac)
  - Firefox: Ctrl + Shift + I (Windows), Cmd + Option + I (Mac)
    - You may need to select the "Console" tab near the top right
- Please take a screenshot of what you see, for example: 
  ![image](https://github.com/nrednav/youtube-playlist-duration-calculator/assets/26251262/d556d796-8da1-467d-aa66-84b93900190c)

**Comment by Destral1** [comment]
Brave browser
windows
2.1.1
![image](https://github.com/nrednav/youtube-playlist-duration-calculator/assets/47291325/7c64f85b-fc07-43b0-b888-4ce7a2468c86) ![image](https://github.com/nrednav/youtube-playlist-duration-calculator/assets/47291325/004ecb36-d145-412c-917f-512ce5838571)
![image](https://github.com/nrednav/youtube-playlist-duration-calculator/assets/47291325/320e01b7-ce07-4df6-a74b-165503893959)

The issue also occurs in chrome, if that's helpful

**Comment by nrednav** [comment]
Thanks @Destral1. Could you please click on one set of the links `main.js:1:1573`, `main.js:1:8204` and `main.js:1:7725`. They should each open a mini-window towards the right of the browser and highlight a line in the code, something like this:
![image](https://github.com/nrednav/youtube-playlist-duration-calculator/assets/26251262/841010e7-5c3e-4c6c-81b3-61b9100ecefa)
![image](https://github.com/nrednav/youtube-playlist-duration-calculator/assets/26251262/3db3b34d-18c6-4284-baf8-819ce0591968)
Please add screenshots of each here, we should be able to narrow down the cause from it

**Comment by Destral1** [comment]
1573:
![image](https://github.com/nrednav/youtube-playlist-duration-calculator/assets/47291325/fe8ae780-5543-439f-a347-74d3e60e2266)
8204:
![image](https://github.com/nrednav/youtube-playlist-duration-calculator/assets/47291325/889d06e7-aa6e-4081-9f05-8b6df45d5caf)
7725:
![image](https://github.com/nrednav/youtube-playlist-duration-calculator/assets/47291325/bbedaa02-bcd9-4f73-8e4d-c959aa2bf55b)

**Comment by nrednav** [comment]
@Destral1 Okay so it appears to have trouble parsing video timestamps.

Can you confirm that all videos in your Watch Later playlist have a timestamp (hh:mm:ss format)? Are there any videos without a timestamp e.g. videos which are "Upcoming"

Could you please copy & paste the following code in the browser console & take a screenshot of the timestamps:
```javascript
(function(){
  const playlistElement = document.querySelector("ytd-playlist-video-list-renderer #contents");
  if (!playlistElement) return console.error("No playlist found");
  
  const videos = [...playlistElement.getElementsByTagName("ytd-playlist-video-renderer")];
  const timestamps = videos.map(video => {
    const timestamp = video.querySelector("ytd-thumbnail-overlay-time-status-renderer");
    if (timestamp) {
      return timestamp.innerText.trim();
    } else {
      return null;
    }
  });
  console.log(timestamps);
})();
```

For example, this is what my Watch Later playlist has on Firefox. You may need to click the little right arrow next to `Array`:
![image](https://github.com/nrednav/youtube-playlist-duration-calculator/assets/26251262/6b51e829-c30a-461b-a950-2f25ae32b1df)

**Comment by Destral1** [comment]
oh, some videos were upcoming, that's probably the issue then.
![image](https://github.com/nrednav/youtube-playlist-duration-calculator/assets/47291325/3155af90-9b4f-46e2-a846-6f951d7418ea)

**Comment by nrednav** [comment]
Ah, well I am currently working on v2.1.2 with some more fixes, so I will update the extension to treat "Upcoming" videos as 0 seconds as part of that. Will post an update here when it's ready 👍

**Comment by Destral1** [comment]
Thanks!

**Comment by nrednav** [comment]
@Destral1 I've submitted v2.1.2 to Chrome & Firefox. Firefox was approved: https://addons.mozilla.org/en-GB/firefox/addon/youtube-playlist-duration-calc/, and Chrome is pending (can take anywhere between 24-72 hours).

In the meantime you can also access the update via: https://github.com/nrednav/youtube-playlist-duration-calculator/releases/tag/v2.1.2
