### ISSUE TITLE
Playlist duration box doesn't appear in non "watch later" playlists

### ISSUE THREAD

**Issue by pifopi** [nrednav/youtube-playlist-duration-calculator#55]
Hello !

For a few days now, I cannot see the playlist duration box on any non watch later playlist. I tried adding "&ytpdc-debug=true" to the URL and it gives me this :
![image](https://github.com/user-attachments/assets/df668ed1-795a-4680-afd7-caf1d3cc298f)
https://www.youtube.com/playlist?list=PLa2kwLIoLbrd2Yw6d8aFNRsNqPeU2HaGQ&ytpdc-debug=true

I used this playlist to showcase the issue but it really happen to all of them beside watch later playlist.  I tried refreshing the page and it does nothing (but the logs are gone because the argument I just gave disapeared).

Thanks for your amazing plugin !

**Comment by nrednav** [comment]
Hi @pifopi, thank you for reporting this. That's very odd, since it seems to be adding the summary to an invisible element. 

1) May I please know which version of Chrome you are using the extension with?
2) Could you please try running the following commands in the console and seeing what it returns:
```
document.querySelector(".immersive-header-content .metadata-action-bar");
document.querySelector("ytd-playlist-sidebar-renderer #items");
document.querySelector("#ytpdc-playlist-summary-old");
document.querySelector("#ytpdc-playlist-summary-new");
```
3) Do you have any other YouTube related extensions installed that could be hiding certain elements on the page?

**Comment by pifopi** [comment]
1. While checking the version, it updated to latest "Version 127.0.6533.73 (Build officiel) (64 bits)" and I can confirm I do still have the issue
2. It returns null which I guess isn't good news for me (but on the watch later playlist, where it works fine, I do have something that get returned + it highlights the div)
![image](https://github.com/user-attachments/assets/4dbd9c04-90a6-4aa5-9a1c-d09471151dd4)
3. I have a few but I tried to disable them all, it did not fix my issue
![image](https://github.com/user-attachments/assets/1858db70-7b6d-4b41-83f5-406d5190a706)

I'll try to investigate more, now that I know which div is missing and I'll share here if i find anything !


EDIT : that was quick, in **_const addPlaylistSummaryToPage = ({_**, **_metadataElement_** is null, so we do an early return and nothing get added to the page. It is trying to use the new design but **_document.querySelector(".immersive-header-content .metadata-action-bar")_** doesn't find anything.

EDIT 2: Just found out that disconnecting myself from youtube does fix my issue. It may be because I do have youtube premium and it somehow change the page

**Comment by pifopi** [comment]
/html/body/ytd-app/div[1]/ytd-page-manager/ytd-browse/ytd-playlist-header-renderer
has some child on my watch later playlist (or without youtube premium) but with youtube premium on a non WL playlist, it is not a leaf
/html/body/ytd-app/div[1]/ytd-page-manager/ytd-browse/yt-page-header-renderer
This might be the replacement ? The box pretty much match but I'm way too inexperienced with HTML to dig much more than this

![image](https://github.com/user-attachments/assets/0ef62e87-9274-4468-a343-46b106e6ca0f)

**Comment by nrednav** [comment]
Hi @pifopi, thanks for replying!

Sorry I should have been more specific for step 2, you'd want to run those commands 1 at a time 😅 

Just out of curiosity, does any video in the playlist have a missing channel name?

**Comment by pifopi** [comment]
Thanks for your help !
![image](https://github.com/user-attachments/assets/8eaa1f66-b522-46df-ae8a-1e96dff1e4c8)
It gives me this

No, all videos have a channel name. I created a new playlist with only one video here if that helps
https://www.youtube.com/playlist?list=PL3f0rMP_u9WtndcAeJQFdsBg8HKbCersv

**Comment by nrednav** [comment]
I think you may be right about the page layout being different for YouTube premium.

The selector for the `metadata` element is supposed to be: `.immersive-header-content .metadata-action-bar` but from your screenshot it is returning null. If you try the same command when you've disconnected from YouTube premium, it should not return null.

This is the element (using Firefox to highlight it):
![image](https://github.com/user-attachments/assets/f1660f5a-0e40-4bf0-86c7-334c35c9a778)

Are you able to find a similar element to this? To make this extension work for YouTube premium, we would need 2 things:
- The classname/id of the same type of element as the screenshot above
- The classname/id of some element on the page that only shows up when you have YouTube premium
  - This will serve as a hook for the extension to decide it should use a different selector and not the normal one

**Comment by pifopi** [comment]
I guess it would be the closest match ?
![image](https://github.com/user-attachments/assets/750fdedb-82f0-42a4-9981-52da0ce84a73)
/html/body/ytd-app/div[1]/ytd-page-manager/ytd-browse/yt-page-header-renderer/yt-page-header-view-model/div[2]/div[1]/div/yt-content-metadata-view-model
class="page-header-view-model-wiz__page-header-content-metadata page-header-view-model-wiz__page-header-content-metadata--page-header-content-metadata-overlay yt-content-metadata-view-model-wiz"

For the element specific to youtube premium, I'd say the button to download a video.
![image](https://github.com/user-attachments/assets/bdd5684d-8f77-402c-90fa-95743a064339)
/html/body/ytd-app/div[1]/ytd-page-manager/ytd-browse/yt-page-header-renderer/yt-page-header-view-model/div[2]/div[2]/yt-flexible-actions-view-model/div/div[4]/download-button-view-model/button-view-model/button/yt-touch-feedback-shape/div/div[2]
class="yt-spec-touch-feedback-shape__fill"

Don't heistate to ask me any more information, I'll head to bed now though as it's 1h41AM local time !

**Comment by nrednav** [comment]
Hi @pifopi, I've created this PR https://github.com/nrednav/youtube-playlist-duration-calculator/pull/57 which hopefully has the changes to make this work.

Could you please give it a try and let me know if it works 🙏

**Comment by pifopi** [comment]
Thank you very much for the quick fix ! Sorry for the time it took, I had to install everything (node.js, etc)
It's sadly not working.
![image](https://github.com/user-attachments/assets/4da4764b-3648-4ea7-a7eb-a8e51c1d9141)
I tried to rebuild with
  playlistDownloadButton: "download-button-view-model",
And it finds the button now (I'm not sure if it's good practice though, I have like no knowledge with web dev). I had to rebuild several times though, I'm sure I'm missing something because i have to wipe everything manually and run the "debug chrome", then manually load the extension into my normal chrome for it to work

EDIT : it's super flaky, I have inconsistent result with finding the div to put the playlist duration into

EDIT 2 : I think resizing the windows make div appear/disapear. Also, for the download button, even if it's present it might not be "visible" because not always loaded on time ? That might explain the flakyness I saw but i'll continue to investigate tomorrow

**Comment by pifopi** [comment]
Okay, so first thing "pnpm run build:chrome" doesn't seems to build anything for me but "pnpm run dev" does. I'm not sure why but oh well

I'll do a PR with my code when it's fully working but indeed, playlistMetadataElement is not visible when the window is big but it is when it's smaller :
![image](https://github.com/user-attachments/assets/546705e9-307b-44f1-a140-0428a061236a)
-> in this case, I get the duration box displayed properly
![image](https://github.com/user-attachments/assets/8ed23cc8-d359-4b11-b84e-45584855b292)
-> In this case, I don't

When fullscreen, I could find to put it here :
![image](https://github.com/user-attachments/assets/9abbe34e-cda8-457c-9e61-7f77eb846393)
but all other locations I found so far aren't visible

**Comment by pifopi** [comment]
I couldn't find a location that works fot both but I found this one that works when fullscreen even though it's not exactly the same place as the watch later one :
![image](https://github.com/user-attachments/assets/27feeec1-ed1d-4462-95a8-98a67dc698a6)
![image](https://github.com/user-attachments/assets/4cd160d8-3605-4247-8991-8f59271e2bea)

The pull request is here
https://github.com/nrednav/youtube-playlist-duration-calculator/pull/58

**Comment by nrednav** [comment]
Hi @pifopi, thanks for providing all that info, it's very helpful. I decided to try yt premium myself and it appears the extension still works for me with it. However, the layout it rendered for me does not have any classes like `.yt-flexible-actions-view-model-wiz__action-row` or `yt-content-metadata-view-model`, so it definitely seems like YT is rendering different layouts for different browsers/users 😅

Can you confirm that the changes in your PR: `".yt-flexible-actions-view-model-wiz__action-row"` have been working well for you these past days, without any issues? If yes, I think we can proceed with that

**Comment by pifopi** [comment]
Hello ! Thanks for your help and support ! Yes, it worked for the past 4 days flawlessly on my side. I do hope youtube doesn't have too many versions 😆

**Comment by nrednav** [comment]
Hi @pifopi, I've just submitted v2.2.0 to the Chrome & Firefox extension stores for approval. When the Chrome version has been approved, could you please try it and let me know if it works 🙏

**Comment by pifopi** [comment]
Sure ! I'll keep an eye on it and keep you updated

**Comment by pifopi** [comment]
It's working properly now, thanks a lot for your work 🙏

**Comment by nrednav** [comment]
Nice 👏 , thanks for your contributions too!
