### ISSUE TITLE
No longer works with new YouTube design

### ISSUE THREAD

**Issue by addmitt** [nrednav/youtube-playlist-duration-calculator#8]
Extension has stopped working with the new YouTube design.

Should be a simple enough fix. The same style of duration boxes appear to be on the pages.

![image](https://user-images.githubusercontent.com/419833/196811869-c5540fb5-37f8-474f-99fa-29c69b1b8480.png)

Seems to specifically fail on the `getPlaylistLength` function in `content.js`, presumably because this tag no longer works to find the spot where it renders the duration:

```
"#stats.style-scope.ytd-playlist-sidebar-primary-info-renderer"
```

Because the spot that it used to dump the duration stats no longer exists according to their selectors (Can't tell if it's #title, #stats, or #title-form, but none of those exist anymore).

**Comment by Moawiah188** [comment]
Works now!
And the new design is absolutely amazing.
